apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka2
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo1/kafka2/
    repoURL: https://github.com/crosscode-nl/gitdevopsdemos
    targetRevision: HEAD
  syncPolicy:
    automated: {}
