apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.4.12
    chart: minio
    helm:
      parameters:
        - name: accessKey.password
          value: ''
  project: 'minio'

