apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minio
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: minio
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - '*'
