apiVersion: v1
kind: PersistentVolume
metadata:
  name: node4pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  nodeAffinity:
    selector:
      matchLabels:
        name: "node4"

