apiVersion: v1
kind: PersistentVolume
metadata:
  name: node8pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  selector:
    matchLabels:
      name: "node8"

