apiVersion: v1
kind: PersistentVolume
metadata:
  name: node4pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/volumeclaim
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node4

