apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - type: persistent-claim
        size: 5Gi
        class: local
        deleteClaim: false
        id: 0
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      class: local
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
